<?php
define('ROOT_PATH','/home/citecrm/public_html/');
define('ROOT_URL','http://www.citecrm.com');
define('SSL_URL','https://www.citecrm.com');
define('DB_HOST', 'localhost');
define('DB_USER', 'citecrm_admin'); 
define('DB_PASS', 'admin');
define('DB_NAME', 'citecrm_citecrm');
define('SITE_NAME',  '');
define('COMPANY_EMAIL','admin@citecrm.com');
define('SITE_EMAIL_ADMIN','');
define('SITE_SLOGAN','Go ahead');
define('DEFAULT_LANGUAGE','en');
define('COMPANY_STREET_1','aaaaaa 4');
define('COMPANY_STREET_2','');
define('COMPANY_CITY','22222');
define('COMPANY_STATE','2222');
define('COMPANY_POSTAL_CODE','2222');
define('COMPANY_COUNTRY','2222');
define('COMPANY_PHONE','2222222');
define('COMPANY_MOBILE','');
define('COMPANY_TOLL_FREE','');
define('COMPANY_FAX','');
define('COMPANY_EMAIL','admin@citecrm.com');
define('DEFAULTAREACODE','222');
define('DEFAULT_STATE','2222');
define('DEFAULT_COUNTRY','2222');
define('DEFAULT_ZIP','2222');
define('SITE_EMAIL','admin@citecrm.com');
define('COMPANY_START_HOUR','09');
define('COMPANY_START_MIN','00');
define('COMPANY_END_HOUR','17');
define('COMPANY_END_MIN','00');
define('SESSION_TIMEOUT','3600');
define('DEFAULT_CALL_COST_PER_MIN','1.00');
define('COMPANY_LOGO','logo.jpg');
define('COMPANY_SMTP_SERVER', '');
define('COMPANY_SMTP_USER', '');
define('COMPANY_SMTP_PASSWORD', '');
define('COMPANY_SMTP_FROM', '');
define('COMPANY_SMTP_REPLY', '');
define('PDF_PRINTING', '1');
define('DISPLAY_COMPANY_LOGO', '1');
define('SYSTEMLABEL', 'dymo_4_2_5_16');
define('DATE_TIME_FORMAT', '%H:%M %m-%d-%Y');
define('DATE_FORMAT', '%m-%d-%Y');
?>