<?php
define('WORKORDER_DISCLAIMER', 
"SERVICE REQUEST AGREEMENT: ".SITE_NAME.", its employees or agents (hereinafter ".SITE_NAME.") will perform the services listed under Work Description above, and any other services as requested. This may include opening the case of computers and/or peripherals for the purposes of testing, inspection, and/or repair at your risk. You authorize ".SITE_NAME." to make any requested repairs for which you agree to make full payment upon the receipt of an invoice detailing the services performed.

SERVICE REQUISITION: You authorize and agree to pay for work performed by ".SITE_NAME.", including payment for parts, under the terms stated herein and at your risk. YOU UNDERSTAND THAT YOU ARE RESPONSIBLE FOR MAKING COPIES OF ALL DATA AND ".SITE_NAME." WILL NOT BE HELD RESPONSIBLE FOR LOSS OF DATA, OR MALFUNCTION, DAMAGE TO,OR LOSS OF HARDWARE AND/OR SOFTWARE OR FAILURE TO MAINTAIN CONFIDENTIALITY OF DATA.

".SITE_NAME." is not liable for and you agree to hold ".SITE_NAME." harmless from any and all damages, costs, and expenses incurred as the result of any error, negligence, defect or damage to any hardware, software, data, or premises (including any property located on the premises) where service has been performed, whether incurred during the course of ".SITE_NAME." services or otherwise.

LIMITATION OF LIABILITY: IN NO EVENT WILL ".SITE_NAME." BE LIABLE FOR DIRECT, INDIRECT, SPECIAL, INCIDENTAL, OR CONSEQUENTIAL DAMAGES OF ANY NATURE AND HOWEVER CAUSED, INCLUDING WITHOUT LIMITATION LOSS OF USE, LOST PROFITS OR REVENUE, OR ANY OTHER DAMAGES WHATSOEVER ARISING IN ANY WAY FROM SERVICES PERFORMED HEREUNDER. IN NO CASE WILL ".SITE_NAME." TOTAL CUMULATIVE LIABILITY FOR DAMAGES AND/OR COSTS FOR ANY AND ALL CLAIMS UNDER ANY THEORY OF LAW WITH RESPECT TO THIS AGREEMENT AND THE SERVICES PERFORMED HEREUNDER EXCEED THE AMOUNT PAID TO ".SITE_NAME." FOR SUCH SERVICES. YOU UNDERSTAND THAT THESE LIMITATIONS OF ".SITE_NAME." LIABILITY ARE A FUNDAMENTAL PART OF THIS AGREEMENT AND THAT ".SITE_NAME." WOULD NOT PROVIDE SERVICE WITHOUT YOUR CONSENT TO THEM.

You understand that your sole remedy if you are not completely satisfied with any service performed shall be a refund of any service charges, less any charges for parts. Any returned hardware or parts will be subject to a 25% restocking fee. You are solely responsible for maintaining legal software licenses. Any controversy or claim arising out of or relating to this Agreement or the breach thereof will be settled by arbitration in accordance with the rules of the American Arbitration Association, with venue in  the state of ".DEFAULT_STATE." and judgment upon the award rendered by the arbitrator may be entered in any court having jurisdiction thereof. This Agreement will be governed by and construed in accordance with the laws of the State of ".DEFAULT_STATE.".

I have read and understand the above Agreement, and am authorized to execute this Agreement and request ".SITE_NAME." to performservices under its terms:");
?>