<?php
@define('DISPLAY_USERS', 1);
$smarty->assign('DISPLAY_USERS', DISPLAY_USERS);
@define('DISPLAY_ACTIVE_WORKORDERS', 1);
$smarty->assign('DISPLAY_ACTIVE_WORKORDERS', DISPLAY_ACTIVE_WORKORDERS);
@define('DISPLAY_ACTIVE_SYSTEMS',1);
$smarty->assign('DISPLAY_ACTIVE_SYSTEMS', DISPLAY_ACTIVE_SYSTEMS);

?>